instance-service:
  build:
    context: ./instanceservice
  container_name: instance-service
  depends_on:
    - rabbitmq
  environment:
    SPRING_RABBITMQ_HOST: rabbitmq
    SPRING_RABBITMQ_PORT: 5672
    SPRING_RABBITMQ_USERNAME: user
    SPRING_RABBITMQ_PASSWORD: userpass
  networks:
    - backend
